### PR TITLE
Create framework project for Carthage support

### PR DESCRIPTION
**Pull request by Dschee**
This commit adds support for installing this library via Carthage by adding this line (once merged & new release published):

```
github "arashpayan/appirater" ~> 2.1
```

Until it's merged you can use my fork with this line instead:

```
github "Dschee/appirater" "master"
```

### CODE REVIEW

**Comment by abakhtin** [comment]
Thanks a lot for this PR. 
I want to ask the owner to review it once again :)

**Comment by arashpayan** [comment]
Hey @Dschee. Thank you for sending this PR. I'm have a little time to spend on Appirater, and I'd like to merge this.

I've never published a Carthage framework before, and though this will merge cleanly, do you know if the presence of the `xcodeproj` will interfere with Cocoapods?

It looks like the only time the framework project would need to change is if a new file(s) is added to the project or if a project is deleted. Is that accurate?

**Comment by Dschee** [comment]
The presence of xcodeproj doesn't interfere with CocoaPods support, the relevant source files are listed under the key `source_files` in the podspec.

Regarding the work to be done to keep Carthage compatibility: Yes, sounds about right. Of course, the framework target needs to build successfully, but that should usually be the case.

**Comment by arashpayan** [comment]
Thanks, @Dschee!

**Comment by mshibanami** [comment]
@Dschee 
This PR still hasn't been in the latest version.
Updating the version from `2.3.1` would be nice if there are no problem.

**Pull request merged**
