### PR TITLE
Optionally disable the remind me later button

### PR DESCRIPTION
**Pull request by maciekish**
Added a property that disables the remind me later button: `+ (void) setShowsRateLaterButton:(BOOL)showsRateLaterButton`

### CODE REVIEW

**Comment by Blackjacx** [comment]
good idea +1

can I vote up this pull request somewhere?

**Comment by arashpayan** [comment]
I'm sorry for not commenting sooner. I'm hesitant to merge this pull request because I think end users should always have a 'Remind Me Later' option. If someone can make a strong case to convince me otherwise, I'll merge the pull request.

**Comment by maciekish** [comment]
Well, you have 3 votes against one. I think it should be up to each **individual** developer to decide which options they want **their** app to offer.

**Comment by Blackjacx** [comment]
I do not need this anymore. And the remind me later button is user friendly as the author said. It is a good idea to not disable it!

**Comment by arashpayan** [comment]
Individual developers can of course modify the code to their needs as they see fit. But I want to maintain Appirater in such a way that I think is beneficial to end users and developers. Making it easy to restrict end users options isn't something I want to encourage.

**Pull request closed without merging**
