### PR TITLE
Fall back to bundle name if bundle display name is null

### PR DESCRIPTION
**Pull request by IanHoar**

### CODE REVIEW

**Comment by IanHoar** [comment]
screenshot 2015-04-06 12 28 21
screenshot 2015-04-06 12 29 35

**Comment by IanHoar** [comment]
https://github.com/arashpayan/appirater/issues/210

**Comment by arashpayan** [comment]
Terrific! Thank you @IanHoar!

**Comment by IanHoar** [comment]
My pleasure.  Thanks for saving me a bunch of time :)

**Pull request merged**
